<?php

namespace HistoryBundle\Repository;

/**
 * adminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adminRepository extends \Doctrine\ORM\EntityRepository{
    
    public function compareLogin($admin){
        $result = $this->findOneBy(array("username" => $admin->getUsername(),
                                        "password" => $admin->getPassword()));
        
        if(empty($result)){
            return false;
        }
        else{
            return $result->getId();
        }
    }
    
}
