<?php

namespace HistoryBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventTypeRepository extends \Doctrine\ORM\EntityRepository{
}
