<?php

namespace HistoryBundle\Repository;

/**
 * histlinkSuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class histlinkSuggestionRepository extends \Doctrine\ORM\EntityRepository
{
}
