<?php

namespace HistoryBundle\Repository;

/**
 * linkHighlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linkHighlightRepository extends \Doctrine\ORM\EntityRepository
{
}
