<?php

namespace HistoryBundle\Repository;

/**
 * linkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linkTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
