<?php

namespace HistoryBundle\Repository;

/**
 * linkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linkRepository extends \Doctrine\ORM\EntityRepository{



}
