<?php

namespace HistoryBundle\Repository;

/**
 * suggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suggestionRepository extends \Doctrine\ORM\EntityRepository
{
}
