<?php

namespace HistoryBundle\Repository;

/**
 * thematiquePersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class thematiquePersonneRepository extends \Doctrine\ORM\EntityRepository
{
}
