<?php

namespace HistoryBundle\Repository;

/**
 * thematiqueCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class thematiqueCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
