services:
#    history.example:
#        class: HistoryBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    history.generator:
        class:    HistoryBundle\Services\Generator